// Generates docs/pages/en/guide/functions.md from the English function catalog
// (packages/core/src/locale/functions/en.ts), the same data that drives
// formula autocomplete and the argument hint.
//
//   bun run docs:functions            rewrite the page
//   bun run docs:functions --check    exit 1 if the page is out of date
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import functionlist from "../../packages/core/src/locale/functions/en";
import {
  FUNCTION_CATEGORIES,
  type FunctionListEntry,
} from "../../packages/core/src/locale/functions/types";

const here = path.dirname(fileURLToPath(import.meta.url));
const target = path.join(here, "..", "pages", "en", "guide", "functions.md");

const categoryLabel: Record<string, string> = {
  Math: "Math and trigonometry",
  Statistical: "Statistical",
  Lookup: "Lookup and reference",
  Database: "Database",
  Date: "Date and time",
  Financial: "Financial",
  Engineering: "Engineering",
  Logical: "Logical",
  Text: "Text",
  Information: "Information",
  Compatibility: "Compatibility",
};

const escapeCell = (s: string) =>
  s.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

function signature(fn: FunctionListEntry): string {
  const args = fn.p.map((p) => {
    const name = p.repeat === "y" ? `${p.name}, ...` : p.name;
    return p.require === "o" ? `[${name}]` : name;
  });
  return `${fn.n}(${args.join(", ")})`;
}

const anchor = (label: string) =>
  label.toLowerCase().replace(/[^a-z0-9]+/g, "-");

function render(): string {
  const byCategory = new Map<number, FunctionListEntry[]>();
  functionlist.forEach((fn) => {
    const list = byCategory.get(fn.t) ?? [];
    list.push(fn);
    byCategory.set(fn.t, list);
  });

  const sections = FUNCTION_CATEGORIES.filter((c) => byCategory.has(c.t));
  const lines: string[] = [
    "# Supported functions",
    "",
    "<!-- Generated by docs/scripts/generate-functions.ts from",
    "     packages/core/src/locale/functions/en.ts. Do not edit by hand;",
    "     run `bun run docs:functions` instead. -->",
    "",
    `TinySheet ships ${functionlist.length} worksheet functions. Every one of them`,
    "appears in formula autocomplete, shows an argument hint while you type,",
    "and is listed in the function search dialog. Arguments in `[brackets]`",
    "are optional; `...` means the argument can be repeated.",
    "",
    "| Category | Functions |",
    "| --- | ---: |",
    ...sections.map((c) => {
      const label = categoryLabel[c.key] ?? c.key;
      return `| [${label}](#${anchor(label)}) | ${
        byCategory.get(c.t)!.length
      } |`;
    }),
    "",
  ];

  sections.forEach((c) => {
    const label = categoryLabel[c.key] ?? c.key;
    const fns = [...byCategory.get(c.t)!].sort((a, b) =>
      a.n.localeCompare(b.n)
    );
    lines.push(
      `## ${label}`,
      "",
      "| Function | Description |",
      "| --- | --- |"
    );
    fns.forEach((fn) => {
      lines.push(
        `| \`${escapeCell(signature(fn))}\` | ${escapeCell(fn.a || fn.d)} |`
      );
    });
    lines.push("");
  });

  return lines.join("\n");
}

const output = render();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // missing file counts as out of date
  }
  if (current !== output) {
    console.error(
      "docs/pages/en/guide/functions.md is out of date; run `bun run docs:functions`."
    );
    process.exit(1);
  }
} else {
  writeFileSync(target, output);
  console.warn(`Wrote ${path.relative(process.cwd(), target)}`);
}
