import React from "react";
import {
  ArrowDownAZ,
  ArrowDownZA,
  ArrowUpDown,
  BadgeCheck,
  ChartColumn,
  ChartSpline,
  Check,
  ChevronRight,
  ClipboardPaste,
  ClipboardList,
  Copy,
  Eraser,
  Eye,
  EyeOff,
  Funnel,
  FunnelX,
  Grid2x2,
  Image,
  Link,
  ListChecks,
  ListFilter,
  MessageSquare,
  MessageSquarePlus,
  MoveHorizontal,
  MoveVertical,
  PaintBucket,
  PanelTop,
  Pencil,
  Plus,
  RefreshCw,
  Scissors,
  Shield,
  ShieldOff,
  StickyNote,
  Table2,
  TableProperties,
  Tag,
  Trash2,
  Unlink,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRightToLine,
  Download,
  FileImage,
  Layers,
  BringToFront,
  SendToBack,
  Type,
  SquarePen,
  Group,
  Rows3,
  Columns3,
  Sigma,
  Percent,
  Hash,
  Replace,
  Baseline,
  CopyPlus,
  FileInput,
  Info,
} from "lucide-react";
import { getIcon, Icon, LucideIcon } from "../ui/icons";

/**
 * Icons of the context menus (cell, header, sheet tab, picture, chart,
 * shape, pivot): the lucide glyphs behind the names features pass as
 * `icon` (`registerContextMenuItem`, `BuiltContextMenuItem`). Unknown names
 * fall back to the chrome icon registry (`registerIcon`).
 */
export const MENU_ICONS: Record<string, LucideIcon> = {
  cut: Scissors,
  copy: Copy,
  paste: ClipboardPaste,
  "paste-special": ClipboardList,
  insert: Plus,
  delete: Trash2,
  clear: Eraser,
  filter: Funnel,
  "filter-clear": FunnelX,
  "filter-value": ListFilter,
  sort: ArrowUpDown,
  "sort-az": ArrowDownAZ,
  "sort-za": ArrowDownZA,
  comment: MessageSquarePlus,
  "comment-view": MessageSquare,
  note: StickyNote,
  format: TableProperties,
  list: ListChecks,
  name: Tag,
  link: Link,
  unlink: Unlink,
  image: Image,
  validation: BadgeCheck,
  chart: ChartColumn,
  sparkline: ChartSpline,
  rowHeight: MoveVertical,
  columnWidth: MoveHorizontal,
  hide: EyeOff,
  unhide: Eye,
  autofit: ArrowLeftRight,
  chevron: ChevronRight,
  check: Check,
  refresh: RefreshCw,
  pivot: Table2,
  table: Table2,
  grid: Grid2x2,
  rename: Pencil,
  edit: SquarePen,
  protect: Shield,
  unprotect: ShieldOff,
  color: PaintBucket,
  "move-left": ArrowLeftToLine,
  "move-right": ArrowRightToLine,
  "move-copy": CopyPlus,
  "select-all": Layers,
  header: PanelTop,
  export: Download,
  "copy-image": FileImage,
  "bring-front": BringToFront,
  "send-back": SendToBack,
  text: Type,
  group: Group,
  rows: Rows3,
  columns: Columns3,
  sum: Sigma,
  percent: Percent,
  number: Hash,
  replace: Replace,
  "font-color": Baseline,
  insertSheet: FileInput,
  info: Info,
};

/** The lucide icon of a context-menu icon name (or a chrome icon name). */
export function menuIcon(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return MENU_ICONS[name] ?? getIcon(name);
}

type Props = { name: string; size?: number };

/** A context-menu icon by name (16px lucide, `currentColor`). */
const MenuIcon: React.FC<Props> = ({ name, size = 16 }) => {
  const glyph = menuIcon(name);
  if (!glyph) return null;
  return <Icon icon={glyph} size={size} />;
};

export default MenuIcon;
