/*
 * Strings of the Home tab's ribbon commands (Excel's names, tooltips and
 * menu entries). Kept next to the commands, like the other feature
 * locales; a language without a translation falls back to English key by
 * key.
 */

const en = {
  // Clipboard
  paste: "Paste",
  pasteShortcut: "Ctrl+V",
  pasteGroup: "Paste",
  pasteValuesGroup: "Paste Values",
  pasteOtherGroup: "Other Paste Options",
  pasteAll: "Paste",
  pasteFormulas: "Formulas",
  pasteFormulasNumber: "Formulas & Number Formatting",
  pasteKeepSource: "Keep Source Formatting",
  pasteNoBorders: "No Borders",
  pasteColumnWidths: "Keep Source Column Widths",
  pasteTranspose: "Transpose",
  pasteValues: "Values",
  pasteValuesNumber: "Values & Number Formatting",
  pasteFormatting: "Formatting",
  pasteLink: "Paste Link",
  pasteSpecial: "Paste Special…",
  pasteSpecialShortcut: "Ctrl+Alt+V",
  pasteDescription: "Add content from the clipboard.",
  cut: "Cut",
  cutShortcut: "Ctrl+X",
  copy: "Copy",
  copyShortcut: "Ctrl+C",
  formatPainter: "Format Painter",
  formatPainterDescription:
    "Copy the formatting of the selection and apply it to other cells. Double-click to keep painting until Esc.",
  // Font
  font: "Font",
  fontSize: "Font Size",
  growFont: "Increase Font Size",
  growFontShortcut: "Ctrl+Shift+>",
  shrinkFont: "Decrease Font Size",
  shrinkFontShortcut: "Ctrl+Shift+<",
  bold: "Bold",
  boldShortcut: "Ctrl+B",
  italic: "Italic",
  italicShortcut: "Ctrl+I",
  underline: "Underline",
  underlineShortcut: "Ctrl+U",
  doubleUnderline: "Double Underline",
  strikethrough: "Strikethrough",
  strikethroughShortcut: "Ctrl+5",
  borders: "Borders",
  bordersDescription: "Apply the last used border to the selection.",
  bordersHeader: "Borders",
  drawBordersHeader: "Line",
  borderBottom: "Bottom Border",
  borderTop: "Top Border",
  borderLeft: "Left Border",
  borderRight: "Right Border",
  borderNone: "No Border",
  borderAll: "All Borders",
  borderOutside: "Outside Borders",
  borderThickBox: "Thick Outside Borders",
  borderInside: "Inside Borders",
  borderBottomDouble: "Bottom Double Border",
  borderBottomThick: "Thick Bottom Border",
  borderTopBottom: "Top and Bottom Border",
  borderTopThickBottom: "Top and Thick Bottom Border",
  borderTopDoubleBottom: "Top and Double Bottom Border",
  lineColor: "Line Color",
  lineStyle: "Line Style",
  moreBorders: "More Borders…",
  fillColor: "Fill Color",
  fillDescription: "Color the background of the selected cells.",
  noFill: "No Fill",
  fontColor: "Font Color",
  fontColorDescription: "Change the color of the text.",
  automatic: "Automatic",
  themeColors: "Theme Colors",
  standardColors: "Standard Colors",
  recentColors: "Recent Colors",
  moreColors: "More Colors…",
  customColor: "Custom color",
  apply: "Apply",
  // Alignment
  topAlign: "Top Align",
  middleAlign: "Middle Align",
  bottomAlign: "Bottom Align",
  alignLeft: "Align Left",
  center: "Center",
  alignRight: "Align Right",
  orientation: "Orientation",
  angleCounterclockwise: "Angle Counterclockwise",
  angleClockwise: "Angle Clockwise",
  verticalText: "Vertical Text",
  rotateUp: "Rotate Text Up",
  rotateDown: "Rotate Text Down",
  formatAlignment: "Format Cell Alignment",
  wrapText: "Wrap Text",
  wrapTextDescription:
    "Wrap extra-long text into multiple lines so you can see all of it.",
  mergeCenter: "Merge & Center",
  mergeCenterDescription:
    "Combine the selected cells into one larger cell and center the contents.",
  mergeAcross: "Merge Across",
  mergeCells: "Merge Cells",
  unmergeCells: "Unmerge Cells",
  decreaseIndent: "Decrease Indent",
  increaseIndent: "Increase Indent",
  // Number
  numberFormat: "Number Format",
  accounting: "Accounting Number Format",
  accountingDescription:
    "Format as dollars, euros or another currency, symbols aligned.",
  moreAccounting: "More Accounting Formats…",
  percentStyle: "Percent Style",
  percentShortcut: "Ctrl+Shift+%",
  commaStyle: "Comma Style",
  increaseDecimal: "Increase Decimal",
  decreaseDecimal: "Decrease Decimal",
  currencies: {
    enUS: "English (United States)",
    enGB: "English (United Kingdom)",
    euro: "Euro (€ 123)",
    zh: "Chinese (PRC)",
    chf: "French (Switzerland)",
    ru: "Russian (Russia)",
    hi: "Hindi (India)",
    zhTW: "Chinese (Taiwan)",
  } as Record<string, string>,
  // Styles
  conditionalFormatting: "Conditional Formatting",
  conditionalFormattingDescription:
    "Highlight interesting cells, emphasize unusual values and visualize data with bars, colors and icons.",
  formatAsTable: "Format as Table",
  formatAsTableDescription:
    "Quickly convert a range of cells to a table with its own style.",
  cellStyles: "Cell Styles",
  cellStylesDescription: "Quickly format a cell by choosing a defined style.",
  // Cells
  insert: "Insert",
  insertCells: "Insert Cells…",
  insertRows: "Insert Sheet Rows",
  insertColumns: "Insert Sheet Columns",
  insertSheet: "Insert Sheet",
  insertDescription: "Add cells, rows, columns or sheets to the workbook.",
  delete: "Delete",
  deleteCells: "Delete Cells…",
  deleteRows: "Delete Sheet Rows",
  deleteColumns: "Delete Sheet Columns",
  deleteSheet: "Delete Sheet",
  deleteDescription: "Delete cells, rows, columns or sheets from the workbook.",
  format: "Format",
  formatDescription:
    "Change the row height or column width, organize sheets, or protect or hide cells.",
  cellSize: "Cell Size",
  rowHeight: "Row Height…",
  autofitRowHeight: "AutoFit Row Height",
  columnWidth: "Column Width…",
  autofitColumnWidth: "AutoFit Column Width",
  visibility: "Visibility",
  hideUnhide: "Hide & Unhide",
  hideRows: "Hide Rows",
  hideColumns: "Hide Columns",
  hideSheet: "Hide Sheet",
  unhideRows: "Unhide Rows",
  unhideColumns: "Unhide Columns",
  unhideSheet: "Unhide Sheet…",
  organizeSheets: "Organize Sheets",
  renameSheet: "Rename Sheet",
  renameSheetTitle: "Rename Sheet",
  sheetName: "Sheet name",
  moveCopySheet: "Move or Copy Sheet…",
  tabColor: "Tab Color",
  noColor: "No Color",
  protection: "Protection",
  protectSheet: "Protect Sheet…",
  unprotectSheet: "Unprotect Sheet…",
  lockCell: "Lock Cell",
  formatCells: "Format Cells…",
  formatCellsShortcut: "Ctrl+1",
  ok: "OK",
  cancel: "Cancel",
  // Editing
  autoSum: "AutoSum",
  autoSumShortcut: "Alt+=",
  autoSumDescription:
    "Automatically add it up. Your total appears after the selected cells.",
  sum: "Sum",
  average: "Average",
  countNumbers: "Count Numbers",
  max: "Max",
  min: "Min",
  moreFunctions: "More Functions…",
  fill: "Fill",
  fillDescription2: "Continue a pattern into one or more adjacent cells.",
  fillDown: "Down",
  fillDownShortcut: "Ctrl+D",
  fillRight: "Right",
  fillRightShortcut: "Ctrl+R",
  fillUp: "Up",
  fillLeft: "Left",
  fillSeries: "Series…",
  flashFill: "Flash Fill",
  flashFillShortcut: "Ctrl+E",
  seriesTitle: "Series",
  seriesIn: "Series in",
  seriesRows: "Rows",
  seriesColumns: "Columns",
  seriesType: "Type",
  seriesLinear: "Linear",
  seriesGrowth: "Growth",
  stepValue: "Step value",
  stopValue: "Stop value",
  clear: "Clear",
  clearDescription:
    "Delete everything in the cell, or remove just the formatting, contents, comments or hyperlinks.",
  clearAll: "Clear All",
  clearFormats: "Clear Formats",
  clearContents: "Clear Contents",
  clearComments: "Clear Comments and Notes",
  clearHyperlinks: "Clear Hyperlinks",
  removeHyperlinks: "Remove Hyperlinks",
  sortFilter: "Sort & Filter",
  sortFilterDescription: "Organize your data so it's easier to analyze.",
  sortAZ: "Sort A to Z",
  sortZA: "Sort Z to A",
  customSort: "Custom Sort…",
  filter: "Filter",
  filterShortcut: "Ctrl+Shift+L",
  clearFilter: "Clear",
  reapply: "Reapply",
  findSelect: "Find & Select",
  findSelectDescription: "Find and select specific text, formatting or cells.",
  find: "Find…",
  findShortcut: "Ctrl+F",
  replace: "Replace…",
  replaceShortcut: "Ctrl+H",
  goTo: "Go To…",
  goToShortcut: "Ctrl+G",
  goToSpecial: "Go To Special…",
  selectFormulas: "Formulas",
  selectNotes: "Notes",
  selectConditional: "Conditional Formatting",
  selectConstants: "Constants",
  selectValidation: "Data Validation",
  noCellsFound: "No cells were found.",
  more: "More options for {name}",
};

export type HomeText = typeof en;

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

const zh: DeepPartial<HomeText> = {
  paste: "粘贴",
  cut: "剪切",
  copy: "复制",
  formatPainter: "格式刷",
  font: "字体",
  fontSize: "字号",
  growFont: "增大字号",
  shrinkFont: "减小字号",
  bold: "加粗",
  italic: "倾斜",
  underline: "下划线",
  doubleUnderline: "双下划线",
  strikethrough: "删除线",
  borders: "边框",
  fillColor: "填充颜色",
  fontColor: "字体颜色",
  topAlign: "顶端对齐",
  middleAlign: "垂直居中",
  bottomAlign: "底端对齐",
  alignLeft: "左对齐",
  center: "居中",
  alignRight: "右对齐",
  orientation: "方向",
  wrapText: "自动换行",
  mergeCenter: "合并后居中",
  decreaseIndent: "减少缩进量",
  increaseIndent: "增加缩进量",
  numberFormat: "数字格式",
  accounting: "会计数字格式",
  percentStyle: "百分比样式",
  commaStyle: "千位分隔样式",
  increaseDecimal: "增加小数位数",
  decreaseDecimal: "减少小数位数",
  conditionalFormatting: "条件格式",
  formatAsTable: "套用表格格式",
  cellStyles: "单元格样式",
  insert: "插入",
  delete: "删除",
  format: "格式",
  autoSum: "自动求和",
  fill: "填充",
  clear: "清除",
  sortFilter: "排序和筛选",
  findSelect: "查找和选择",
};

const es: DeepPartial<HomeText> = {
  paste: "Pegar",
  cut: "Cortar",
  copy: "Copiar",
  formatPainter: "Copiar formato",
  font: "Fuente",
  fontSize: "Tamaño de fuente",
  bold: "Negrita",
  italic: "Cursiva",
  underline: "Subrayado",
  strikethrough: "Tachado",
  borders: "Bordes",
  fillColor: "Color de relleno",
  fontColor: "Color de fuente",
  wrapText: "Ajustar texto",
  mergeCenter: "Combinar y centrar",
  conditionalFormatting: "Formato condicional",
  formatAsTable: "Dar formato como tabla",
  cellStyles: "Estilos de celda",
  insert: "Insertar",
  delete: "Eliminar",
  format: "Formato",
  autoSum: "Autosuma",
  fill: "Rellenar",
  clear: "Borrar",
  sortFilter: "Ordenar y filtrar",
  findSelect: "Buscar y seleccionar",
};

const translations: Record<string, DeepPartial<HomeText>> = {
  zh,
  "zh-CN": zh,
  es,
};

const cache: Record<string, HomeText> = {};

function mergeDeep(base: any, over: any): any {
  if (over == null) return base;
  if (typeof base !== "object" || base == null) return over ?? base;
  const out: any = { ...base };
  Object.keys(over).forEach((k) => {
    out[k] = mergeDeep(base[k], over[k]);
  });
  return out;
}

/** The Home strings for a context's language (English fallback). */
export function homeText(ctx: { lang?: string | null }): HomeText {
  const lang = ctx?.lang || "en";
  const key = [lang, lang.split("-")[0]].find((l) => l in translations) ?? "en";
  if (!cache[key]) cache[key] = mergeDeep(en, translations[key]);
  return cache[key];
}
